### ISSUE TITLE
Tutorial images should be updated for Gregorio 4.2

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio-project.github.io#50]
See https://www.mail-archive.com/gregorio-users@gna.org/msg03784.html and replies for background.

The user is not receiving the results displayed in the tutorial.

**Comment by rpspringuel** [comment]
There are two options here for the correction:
1. Use the old bar spacing algorithm.  In this case the pictures are correct, but a note needs to be added for 4.2 users to let them know they need `\gresetbarspacing{old}` in their tex file.
2. Use the new bar spacing algorithm.  In this case the pictures need updating and a note has to be added for 4.1 users (i.e. those using Gregorio as packaged in TeXLive) letting them know that they need `\gresetbarspacing{new}`.  It might also be necessary to add some steps to the tutorial which tweak the positions of the asterisks by manipulating the appropriate distances with `\grechangedim`.

The first option is less work, so that's what I'm inclined to go with.  The more detailed updates can wait until next year when TeXLive 2017 comes out (and thus support for 4.1 falls by the wayside).

Any other opinions?

**Comment by henryso** [comment]
I'd agree with that plan.
