### ISSUE TITLE
404 in Tutorial and need for image of code...

### ISSUE THREAD

**Issue by MRoth1910** [gregorio-project/gregorio-project.github.io#97]
Hi everyone, 

I'm getting back into chant engraving etc. so I worked through the tutorial. The completed GABC is missing for the final page of the tutorial on the website (it takes you to a 404) and it'd be helpful if the code was also posted as an image alongside the last picture as in the rest of the tutorial, because the spacing issue in "introívit" still exists, and I can't figure out how to place the dot of the punctum over the following punctum (I'm just working on "introívit," as the rest of it worked and made sense). 

As you can see, I figured out the podatus issue, but not the dot, so being able to see the code would be helpful...Thanks. 
<img width="406" alt="Screen Shot 2020-07-25 at 4 57 07 PM" src="https://user-images.githubusercontent.com/68782573/88459802-42d7a100-ce98-11ea-8d85-b69fbde8d79f.png">

**Comment by rpspringuel** [comment]
Link is fixed by 6c6fb487a97efed5e3b54de7f331f00c478000f9.

The code is not shown in the image because we're dealing with the downloaded file at this point, not the preview in the interface.  The change in the images is meant to highlight that fact and keep people from being confused about what to look at.
